export const de = {
  nav: { massages: 'Massagen', story: 'Über Nipa', cosmetics: 'Kosmetik', contact: 'Kontakt', menu: 'Menü öffnen', close: 'Menü schließen' },
  hero: { eyebrow: 'Thaimassage & Kosmetik · Mannheim', line1: 'Ein Stück', line2: 'Thailand.', line3: 'Mitten in Mannheim.', copy: 'Traditionelle Thaimassage, wohltuende Ölmassagen und Kosmetik im Herzen Mannheims.', book: 'Termin anfragen', discover: 'Massagen entdecken', location: 'R1,14 · Mannheim', imageAlt: 'Traditionelle thailändische Kräuterstempel' },
  massages: { eyebrow: 'Behandlungen', title: 'Berührung mit Tradition.', intro: 'Von der klassischen Thaimassage bis zum warmen Kräuterstempel: Wählen Sie die Auszeit, die heute zu Ihnen passt.', all: 'Alle Massagen & Preise', less: 'Weniger anzeigen', minute: 'Minuten' },
  story: { eyebrow: 'Die Person hinter Nipa', title1: 'Von Thailand', title2: 'nach Mannheim.', p1: 'Nipa wurde in Thailand geboren und lebt seit 1996 in Deutschland. 2013 absolvierte sie ihre Thaimassage-Ausbildung an der renommierten Wat-Pho-Schule in Bangkok und bildete sich anschließend weiter.', p2: 'Ihre Idee ist einfach: Gäste persönlich willkommen heißen, ihnen eine echte Pause schenken und ein kleines Stück Thailand nach Mannheim bringen.', year: 'Bangkok · Wat Pho', quote: '„Ich liebe es, meine Gäste willkommen zu heißen und ihnen das Gefühl zu geben, dass sie in guten Händen sind.“' },
  signature: { eyebrow: 'Signature Ritual', title1: 'Kräuter-', title2: 'stempel.', copy: 'Warme, duftende Kräuterkompressen gleiten entlang der Muskulatur. Ein traditionell inspiriertes Ritual, das Wärme und Ruhe verbindet.', duration: '60 / 90 Minuten', price: '75 / 100 €', imageAlt: 'Warme Kräuterstempel für eine traditionelle Massage' },
  cosmetics: { eyebrow: 'Kosmetik Studio', title: 'Mehr als Massage.', copy: 'Eine ruhige, sorgfältige Pflege für Hände und Füße – als kleine Auszeit für sich oder als Ergänzung zum Massagebesuch.' },
  trust: { eyebrow: 'Kundenstimme', quote: '„Für mich eine der besten Thaimassagen in Mannheim.“', author: 'Basti', note: 'Kundenmeinung von der bisherigen Nipa-Website' },
  contact: { eyebrow: 'Termin & Anfahrt', title1: 'Ihre Auszeit', title2: 'beginnt hier.', address: 'Adresse', hours: 'Öffnungszeiten', hoursValue: 'Montag–Samstag', phone: 'Telefon', whatsapp: 'WhatsApp', route: 'Route planen', book: 'Termin per WhatsApp anfragen', note: 'Termine nach Anfrage. Keine Erotikmassagen.' },
  footer: { top: 'Nach oben', legal: 'Impressum & Datenschutz werden zur finalen Übergabe ergänzt.', rights: 'Nipa Thaimassage & Kosmetik' },
  common: { newWindow: 'Öffnet in einem neuen Tab', language: 'Sprache wählen', navigation: 'Hauptnavigation' },
} as const
