export const en = {
  nav: { massages: 'Massages', story: 'About Nipa', cosmetics: 'Beauty care', contact: 'Contact', menu: 'Open menu', close: 'Close menu' },
  hero: { eyebrow: 'Thai massage & beauty · Mannheim', line1: 'A touch of', line2: 'Thailand.', line3: 'In central Mannheim.', copy: 'Traditional Thai massage, soothing oil treatments and beauty care in the heart of Mannheim.', book: 'Request appointment', discover: 'Explore massages', location: 'R1,14 · Mannheim', imageAlt: 'Traditional Thai herbal compresses' },
  massages: { eyebrow: 'Treatments', title: 'A tradition of touch.', intro: 'From classic Thai massage to warm herbal compresses: choose the moment of rest that feels right today.', all: 'All massages & prices', less: 'Show less', minute: 'Minutes' },
  story: { eyebrow: 'The person behind Nipa', title1: 'From Thailand', title2: 'to Mannheim.', p1: 'Born in Thailand, Nipa has lived in Germany since 1996. In 2013 she completed her Thai massage training at Bangkok’s renowned Wat Pho school and continued with further training.', p2: 'Her idea is simple: welcome every guest personally, create a genuine pause and bring a small touch of Thailand to Mannheim.', year: 'Bangkok · Wat Pho', quote: '“I love welcoming my guests and making them feel that they are in good hands.”' },
  signature: { eyebrow: 'Signature ritual', title1: 'Herbal', title2: 'compress.', copy: 'Warm, aromatic herbal compresses move along the muscles. A traditionally inspired ritual that brings warmth and calm together.', duration: '60 / 90 minutes', price: '75 / 100 €', imageAlt: 'Warm herbal compresses for a traditional massage' },
  cosmetics: { eyebrow: 'Beauty studio', title: 'Beyond massage.', copy: 'Calm, careful treatment for hands and feet — a small moment for yourself or a complement to your massage visit.' },
  trust: { eyebrow: 'Guest words', quote: '“For me, one of the best Thai massages in Mannheim.”', author: 'Basti', note: 'Customer review from Nipa’s previous website' },
  contact: { eyebrow: 'Appointments & directions', title1: 'Your time out', title2: 'starts here.', address: 'Address', hours: 'Opening hours', hoursValue: 'Monday–Saturday', phone: 'Telephone', whatsapp: 'WhatsApp', route: 'Plan route', book: 'Request via WhatsApp', note: 'Appointments by request. No erotic massages.' },
  footer: { top: 'Back to top', legal: 'Legal notice and privacy policy will be added for final handover.', rights: 'Nipa Thaimassage & Kosmetik' },
  common: { newWindow: 'Opens in a new tab', language: 'Choose language', navigation: 'Main navigation' },
} as const
